version: "3.8"                                                 # lines of the unused services simply deleted. Changes commented, everything else same
services:

  frontend:
    image: reallibrephotos/librephotos-frontend:${tag}
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: reallibrephotos/librephotos:${tag}
    container_name: backend
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - ${scanDirectory}:/data
      - ${data}/protected_media:/protected_media
      - /var/log/librephotos:/logs                                # changed to the default Ubuntu / Arch logs path.
      - ${data}/cache:/root/.cache
      - ${data}/nextcloud_media:/nextcloud_media                  # added for Nexctloud files.
      - /run/redis/redis-server.sock:/run/redis/redis-server.sock # Ubuntu REDIS socket path. On ArchLinux remove this line
      - /run/redis/redis.sock:/run/redis/redis.sock               # Arch REDIS socket path. On Ubuntu/Debian remove this line
    environment:
      - SECRET_KEY=${shhhhKey}
      - BACKEND_HOST=localhost
      - ADMIN_EMAIL=${adminEmail}
      - ADMIN_USERNAME=${userName}
      - ADMIN_PASSWORD=${userPass}
      - DB_BACKEND=postgresql
      - DB_NAME=${dbName}
      - DB_USER=${dbUser}
      - DB_PASS=${dbPass}
      - DB_HOST=${dbHost}
      - DB_PORT=5432
      - REDIS_PATH=/run/redis/redis-server.sock                   # Redis socket connection.
      - MAPBOX_API_KEY=${mapApiKey:-}
      - WEB_CONCURRENCY=${gunniWorkers:-1}
      - SKIP_PATTERNS=${skipPatterns:-}
      - ALLOW_UPLOAD=${allowUpload:-false}
      - CSRF_TRUSTED_ORIGINS=${csrfTrustedOrigins:-}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${HEAVYWEIGHT_PROCESS:-}
